using System;
using System.Collections.Generic;
using System.Text.Json.Nodes;

namespace ReverseCampus
{
    public class Setting
    {
        public string                   Id;                             // 24
        public int                      GiftDefaultLimitCount;          // 32
        public int                      GiftHistoryDefaultLimitCount;   // 36
        public int                      MeishiLimitCount;               // 40
        public int                      MeishiObjectLimitCount;         // 44
        public int                      MeishiFolderLimitCount;         // 48
        public int                      NewLabelTTL;                    // 52
        public int                      WorkSkipLimit;                  // 56
        public int                      WorkSkipConsumeMinutes;         // 60
        public int                      ProfileBirthdayUpdateIntervalDays; // 64
        public int                      ResetTimingHour;                // 68
        public int                      ResetTimingMinute;              // 72
        public string                   ResetTimingWeek;                // 80
        public int                      ResetTimingDay;                 // 88
        public string                   InitialUserMeishiBaseAssetID;   // 96
        public int[]                    RosterIgnoreReportDearnessLevels; // 104
        public int                      MemoryLimitCount;               // 112
        public int                      PhotoLimitCount;                // 116
        public int                      ActionPointRecoveryMinutes;     // 120
        public int                      ActionPointMaxValue;            // 124
        public int                      MoneyHomeDisplayPermil;         // 128
        public int                      MoneyReceivableMinimumMinutes;  // 132
        public int                      WorkExcellentRewardQuantityCoefficientPermil; // 136
        public long                     FanCountLimit;                  // 144
        public int                      WorkFineCharacterMaxCountInDay; // 152
        public int                      WorkFineProbabilityPermil;      // 156
        public int                      WorkFineFixDays;                // 160
        public int                      FriendBaseFollowLimitCount;     // 164
        public int                      FriendFollowerLimitCount;       // 168
        public int                      FriendCoinMaxDailyAccumulationCount; // 172
        public int                      FriendCoinSupportCardRentalRewardQuantity; // 176
        public int                      FriendCoinMemoryRentalRewardQuantity; // 180
        public int                      MemoryPowerParameterCoefficientPermil; // 184
        public int                      MemoryPowerStaminaCoefficientPermil; // 188
        public int                      MemoryPowerProduceResourceEvaluationCoefficientPermil; // 192
        public string                   SeminarExamSettingID;           // 200
        public string                   InitialUserName;                // 208
        public string                   TowerExamSettingID;             // 216
        public int                      CoinGashaNoticeDrawCount;       // 224
        public string                   JewelShopID;                    // 232
        public int                      MissionPassPointExchangeJewel;  // 240
        public string                   OfficialXURL;                   // 248
        public string                   IosFaqURL;                      // 256
        public string                   AndroidFaqURL;                  // 264
        public string                   InitialAchievementID;           // 272
        public int                      InviteUserActiveMaxCount;       // 280
        public int                      InvitationEnterCodeRewardJewelQuantity; // 284
        public string                   InvitationEnterCodeRewardProvideConditionSetID; // 288
        public string                   IosInquiryURL;                  // 296
        public string                   AndroidInquiryURL;              // 304
        public string                   InvitationEnterCodeConditionSetID; // 312
        public string                   UserDeleteInquiryURL;           // 320
        public string                   InvitationNoticeID;             // 328
        public string                   BanWarningMessage;              // 336
        public int                      SeminarInitialParameter;        // 344
        public int                      MemoryCreateAbilityRToSsrPermil; // 348
        public int                      MemoryCreateAbilitySrToSsrPermil; // 352
        public int                      MemoryCreateProduceCardSrToSsrPermil; // 356
        public int                      MemoryCreateExamBattleProduceCardSrToSsrPermil; // 360
        public int                      MusicHotDisplayCount;           // 364
        public string                   HomeDailyMissionGroupID;        // 368
        public string                   HomeWeeklyMissionGroupID;       // 376
        public int                      MemoryCreateParameterSmall;     // 384
        public int                      MemoryCreateParameterMiddle;    // 388
        public int                      MemoryCreateParameterLarge;     // 392
        public string                   TowerViewConditionSetID;        // 400
        public string                   SeminarViewConditionSetID;      // 408
        public string[]                 StoryEventTipsAssetIDs;         // 416
        public int                      StoryEventPointLimit;           // 424
        public string                   SeminarGuidanceViewConditionSetID; // 432
        public string                   OfficialWebSiteURL;             // 440
        public string                   IPPortalWebSiteURL;             // 448
        public int                      PhotoNameLengthLimit;           // 456
        public int                      HomeEventEndTimeDisplayHour;    // 460
        public string                   IdolCardPieceExchangeItemID;    // 464
        public string[]                 StoryEventMainStoryTipsAssetIDs; // 472
        public string                   OfficialDiscordURL;             // 480
        public string                   OfficialYouTubeIdolMasterURL;   // 488
        public string                   OfficialYouTubeHatsuBoshiURL;   // 496
        public string[]                 StoryEventGuildMissionTipAssetIDs; // 504
        public int                      PhotoPoseWaitVoicePlayIntervalSeconds; // 512
        public string                   PhotoBackgroundDefaultBGMAssetID; // 520
        public int                      PhotoMaxShootingCount;          // 528
        public int                      PhotoAutoShootingCount;         // 532
        public string                   MeishiEditCustomUnlockConditionSetID; // 536
        public string                   PhotoIdolViewConditionSetID;    // 544
        public int                      GvgRaidScoreEffectMiddleThreshold; // 552
        public int                      GvgRaidScoreEffectLargeThreshold; // 556
        public int                      GvgRaidAuditionScoreUpMiddle;   // 560
        public int                      GvgRaidAuditionScoreUpLarge;    // 564
        public string                   PhotoFacialViewConditionSetID;  // 568
        public string                   MemoryReshootingValidateIdolCardTrueEndConditionSetID; // 576
        public string                   GashaAnimationLogicSwitchConditionSetID; // 584
        public string                   MeishiEditCustomUpdateUnlockConditionSetID; // 592
        public string                   DmmGamesFaqURL;                 // 600
        public string                   DmmGamesInquiryURL;             // 608
        public int                      TowerRankingDisplayCount;       // 616
        public int                      TowerRankingDeckDisplayCount;   // 620
        public string                   DearnessTopConditionSetID;      // 624
        public string                   LiveLightAnchorEnableConditionSetID; // 632
        public int                      ProduceDailyMemoryRentalLimit;  // 640
        public int                      ProduceDailyFreeContinueCount;  // 644
        public string                   ProduceContinueItemID;          // 648
        public int                      ProduceStartShopWarningProducePointQuantity; // 656
        public int                      ProduceParameterOutGameDisplayLimit; // 660
        public int                      ProduceParameterInGameDisplayLimit; // 664
        public int                      ProducePointLimit;              // 668
        public int                      ProduceMaxStaminaLimit;         // 672
        public int                      ProduceCardLimitCount;          // 676
        public int                      ProduceRankingDisplayCount;     // 680
        public int                      ProduceAuditionScoreUpMiddle;   // 684
        public int                      ProduceAuditionScoreUpLarge;    // 688
        public int                      ProduceExamBattleScorePenaltyMinPermil; // 692
        public int                      ProduceExamBattleScorePenaltyMaxPermil; // 696
        public int[]                    ProduceSupportCardRecommendLevelCoefficientPermils; // 704
        public int                      ProduceSupportCardRecommendTypeNegativeCoefficientPermil; // 712
        public string                   ProducePictureBookLiveProduceGroupID; // 720
        public int                      ProduceRevealSpLessonStepCount; // 728
        public string                   Produce3DTapSkipConditionSetID; // 736
        public int                      ProduceLessonParameterUpMiddle; // 744
        public int                      ProduceLessonParameterUpLarge;  // 748
        public int                      ProduceExamProduceCardSuggestMinutes; // 752
        public int                      ProduceScheduleSelectPlaceStaminaThreshold; // 756
        public int                      ProduceMemoryRerollCount;       // 760
        public int                      ProduceDeckNameLengthLimit;     // 764
        public bool                     ProduceDescriptionProduceStepCategoryEnable; // 768
        public bool                     ProduceCardEffectCancelEnable;  // 769
        public bool                     ProduceMemoryProduceCardProducerLevelLimitDisable; // 770
        public int[]                    ProduceSupportCardRecommendUsageRateRankAdditionValues; // 776
        public int[]                    ProduceSupportCardRecommendTypePreferentialSlotCounts; // 784
        public int                      ProduceSupportCardRecommendTypePreferentialCoefficientPermil; // 792
        public int[]                    ProduceSupportCardRecommendSpPreferentialSlotCounts; // 800
        public int                      ProduceSupportCardRecommendSpPreferentialCoefficientPermil; // 808
        public int                      MemoryCreateAbilityRToUrPermil; // 812
        public int                      MemoryCreateAbilitySrToUrPermil; // 816
        public int                      MemoryCreateAbilitySsrToUrPermil; // 820
        public bool                     ProduceStepShopDiscountRoundDownEnable; // 824
        public int                      GashaPickupStoryCampaignCharacterDearnessLevel; // 828
        public int                      GashaAnimationReversalSsrPermil; // 832
        public int                      GashaAnimationReversalPickUpProduceIdolSsrPermil; // 836
        public int                      TutorialSetNameAdvIndex;        // 840
        public string                   TutorialIdolCardSkinSelectRewardID; // 848
        public int                      ShopPurchasableLimitAmountThreshold1; // 856
        public int                      ShopPurchasableLimitAmountThreshold2; // 860
        public int                      ShopPurchaseAlertThreshold;     // 864
        public int                      JewelMaxQuantityForPaid;        // 868
        public int                      JewelMaxQuantityForFree;        // 872
        public int                      ShopPurchasableLimitAgeThreshold1; // 876
        public int                      ShopPurchasableLimitAgeThreshold2; // 880
        public int                      ShopExpireEmphasisHour;         // 884
        public int                      GuildMemberLimitCount;          // 888
        public int                      GuildJoinRequestLimitCount;     // 892
        public int                      GuildJoinRequestReceiveLimitCount; // 896
        public int                      GuildRestrictJoinHour;          // 900
        public int                      GuildRestrictEstablishHour;     // 904
        public int                      GuildRestrictDonationRequestHour; // 908
        public int                      GuildDonationRequestReceiveMaxQuantity; // 912
        public int                      GuildDonationLimitCount;        // 916
        public int                      GuildNameLengthLimit;           // 920
        public int                      GuildDescriptionLengthLimit;    // 924
        public int                      GuildLeaderMessageLengthLimit;  // 928
        public int                      ProfileNameLengthLimit;         // 932
        public int                      ProfileCommentLengthLimit;      // 936
        public string                   PvpRateSameCharacterDeckConditionSetID; // 944
        public int                      PvpRateMemoryRecommendParameterCoefficientPermil; // 952
        public int                      PvpRateMemoryRecommendStaminaCoefficientPermil; // 956
        public int                      PvpRateMemoryRecommendProduceCardCoefficientPermil; // 960
        public int                      PvpRateMemoryRecommendProduceItemCoefficientPermil; // 964
        public string                   PvpRateExamBattleAllSkipUnlockConditionSetID; // 968
        public string                   PvpRateRehearsalViewConditionSetID; // 976
        public int                      PvpRateRankingDisplayCount;     // 984
        public int                      ExamBattleSubMemoryParameterPermil; // 988
        public int                      ExamBattleSubMemoryStaminaPermil; // 992
        public int                      ExamBattleConditionThresholdMultipleScore; // 996
        public int                      PushDailyMissionNotifyHour;     // 1000
        public int                      PushDailyMissionNotifyMinutes;  // 1004
        public int                      PushDailyMissionDoNotNotifyNoLoginDay; // 1008
        public int                      PushNoLoginNotifyLatestIntervalHour; // 1012
        public int                      PushPvpRateRemainingPlayCountNotifyHour; // 1016
        public int                      PushPvpRateRemainingPlayCountNotifyMinutes; // 1020
        public int                      PushPvpRateRemainingPlayCountDoNotNotifyNoLoginDay; // 1024
        public string                   AprilFool2025TransitionStoryID; // 1032
        public string                   AprilFool2025ProduceLiveMusicID; // 1040
        public string                   ProduceNextIdolAuditionMasterRankingUnlockConditionSetID; // 1048
    }
}
