using System;
using System.Collections.Generic;
using System.Text.Json.Nodes;

namespace ReverseCampus
{
    public enum ProduceCardGrowEffectType
    {
        Unknown,
        LessonAdd,
        LessonReduce,
        LessonCountAdd,
        LessonCountReduce,
        BlockAdd,
        BlockReduce,
        FullPowerPointAdd,
        FullPowerPointReduce,
        CostBuffReduce,
        CostBuffAdd,
        CostReduce,
        CostAdd,
        CostPenetrateReduce,
        CostPenetrateAdd,
        ParameterBuffTurnAdd,
        ParameterBuffTurnReduce,
        LessonBuffAdd,
        LessonBuffReduce,
        ReviewAdd,
        ReviewReduce,
        AggressiveAdd,
        AggressiveReduce,
        CardDrawAdd,
        CardDrawReduce,
        ParameterBuffMultiplePerTurnAdd,
        ParameterBuffMultiplePerTurnReduce,
        StaminaConsumptionDownTurnAdd,
        StaminaConsumptionDownTurnReduce,
        StaminaConsumptionAddTurnAdd,
        StaminaConsumptionAddTurnReduce,
        EffectAdd,
        EffectDelete,
        EffectChange,
        CardStatusEnchantChange,
        PlayTriggerChange,
        PlayEffectTriggerChange,
        PlayMovePositionTypeChange,
        InitialAdd,
        CostLessonBuffReduce,
        CostLessonBuffAdd,
        CostReviewReduce,
        CostReviewAdd,
        CostAggressiveReduce,
        CostAggressiveAdd,
        CostParameterBuffReduce,
        CostParameterBuffAdd,
        CostFullPowerPointReduce,
        CostFullPowerPointAdd,
        LessonDependBlockAdd,
        LessonDependExamCardPlayAggressiveAdd,
        LessonDependExamReviewAdd,
        CostParameterBuffMultiplePerTurnAdd,
        CostParameterBuffMultiplePerTurnReduce,
    }
}
